/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Thu Jun 16 11:04:14 2016. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const int32_t goosci_Version_version_default = 1;


const pb_field_t goosci_Empty_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t goosci_Version_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_Version, version, version, &goosci_Version_version_default),
    PB_LAST_FIELD
};

const pb_field_t goosci_AnalogPin_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_AnalogPin, pin, pin, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_DigitalPin_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_DigitalPin, pin, pin, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_VirtualPin_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_VirtualPin, pin, pin, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_Pin_fields[4] = {
    PB_ONEOF_FIELD(pin,  10, MESSAGE , ONEOF, STATIC  , FIRST, goosci_Pin, analog_pin, analog_pin, &goosci_AnalogPin_fields),
    PB_ONEOF_FIELD(pin,  11, MESSAGE , ONEOF, STATIC  , FIRST, goosci_Pin, digital_pin, digital_pin, &goosci_DigitalPin_fields),
    PB_ONEOF_FIELD(pin,  12, MESSAGE , ONEOF, STATIC  , FIRST, goosci_Pin, virtual_pin, virtual_pin, &goosci_VirtualPin_fields),
    PB_LAST_FIELD
};

const pb_field_t goosci_Interval_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_Interval, count, count, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, goosci_Interval, frequency, count, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_SensorDataRequest_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, goosci_SensorDataRequest, timestamp_key, timestamp_key, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, goosci_SensorDataRequest, interval, timestamp_key, &goosci_Interval_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, goosci_SensorDataRequest, pin, interval, &goosci_Pin_fields),
    PB_LAST_FIELD
};

const pb_field_t goosci_BleSensorConfig_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, goosci_BleSensorConfig, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_AnalogValue_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, goosci_AnalogValue, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_DigitalValue_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, goosci_DigitalValue, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_FloatValue_fields[2] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, goosci_FloatValue, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_IntValue_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, goosci_IntValue, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_StringValue_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, goosci_StringValue, value, value, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_Data_fields[7] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, goosci_Data, pin, pin, &goosci_Pin_fields),
    PB_ONEOF_FIELD(value,  10, MESSAGE , ONEOF, STATIC  , OTHER, goosci_Data, analog_value, pin, &goosci_AnalogValue_fields),
    PB_ONEOF_FIELD(value,  11, MESSAGE , ONEOF, STATIC  , OTHER, goosci_Data, digital_value, pin, &goosci_DigitalValue_fields),
    PB_ONEOF_FIELD(value,  12, MESSAGE , ONEOF, STATIC  , OTHER, goosci_Data, float_value, pin, &goosci_FloatValue_fields),
    PB_ONEOF_FIELD(value,  13, MESSAGE , ONEOF, STATIC  , OTHER, goosci_Data, int_value, pin, &goosci_IntValue_fields),
    PB_ONEOF_FIELD(value,  14, MESSAGE , ONEOF, STATIC  , OTHER, goosci_Data, string_value, pin, &goosci_StringValue_fields),
    PB_LAST_FIELD
};

const pb_field_t goosci_Error_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, goosci_Error, error, error, 0),
    PB_LAST_FIELD
};

const pb_field_t goosci_SensorData_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, goosci_SensorData, timestamp_key, timestamp_key, 0),
    PB_ONEOF_FIELD(result,  10, MESSAGE , ONEOF, STATIC  , OTHER, goosci_SensorData, error, timestamp_key, &goosci_Error_fields),
    PB_ONEOF_FIELD(result,  11, MESSAGE , ONEOF, STATIC  , OTHER, goosci_SensorData, data, timestamp_key, &goosci_Data_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(goosci_Pin, pin.analog_pin) < 65536 && pb_membersize(goosci_Pin, pin.digital_pin) < 65536 && pb_membersize(goosci_Pin, pin.virtual_pin) < 65536 && pb_membersize(goosci_SensorDataRequest, interval) < 65536 && pb_membersize(goosci_SensorDataRequest, pin) < 65536 && pb_membersize(goosci_Data, value.analog_value) < 65536 && pb_membersize(goosci_Data, value.digital_value) < 65536 && pb_membersize(goosci_Data, value.float_value) < 65536 && pb_membersize(goosci_Data, value.int_value) < 65536 && pb_membersize(goosci_Data, value.string_value) < 65536 && pb_membersize(goosci_Data, pin) < 65536 && pb_membersize(goosci_SensorData, result.error) < 65536 && pb_membersize(goosci_SensorData, result.data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_goosci_Empty_goosci_Version_goosci_AnalogPin_goosci_DigitalPin_goosci_VirtualPin_goosci_Pin_goosci_Interval_goosci_SensorDataRequest_goosci_BleSensorConfig_goosci_AnalogValue_goosci_DigitalValue_goosci_FloatValue_goosci_IntValue_goosci_StringValue_goosci_Data_goosci_Error_goosci_SensorData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(goosci_Pin, pin.analog_pin) < 256 && pb_membersize(goosci_Pin, pin.digital_pin) < 256 && pb_membersize(goosci_Pin, pin.virtual_pin) < 256 && pb_membersize(goosci_SensorDataRequest, interval) < 256 && pb_membersize(goosci_SensorDataRequest, pin) < 256 && pb_membersize(goosci_Data, value.analog_value) < 256 && pb_membersize(goosci_Data, value.digital_value) < 256 && pb_membersize(goosci_Data, value.float_value) < 256 && pb_membersize(goosci_Data, value.int_value) < 256 && pb_membersize(goosci_Data, value.string_value) < 256 && pb_membersize(goosci_Data, pin) < 256 && pb_membersize(goosci_SensorData, result.error) < 256 && pb_membersize(goosci_SensorData, result.data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_goosci_Empty_goosci_Version_goosci_AnalogPin_goosci_DigitalPin_goosci_VirtualPin_goosci_Pin_goosci_Interval_goosci_SensorDataRequest_goosci_BleSensorConfig_goosci_AnalogValue_goosci_DigitalValue_goosci_FloatValue_goosci_IntValue_goosci_StringValue_goosci_Data_goosci_Error_goosci_SensorData)
#endif


/* @@protoc_insertion_point(eof) */
